#!/usr/bin/env bash
#
# Backup all the specified files to version control,
# or update the files on this machine with the ones available online.

base_path="$(cd; pwd)/"

buffer_folder="${base_path}ubuntu-dotfiles"

# TODO: Extract this to config file
selected_files=(
  ".hgrc"
  ".vimrc"
  ".hgrc"
  ".gvimrc"
  ".zshrc"
  ".i3"
  ".i3status.conf"
  ".aliases"
  "vimwiki"
  ".profile"
  ".Xdefaults"
)

main() {
  parse_params "$@"
  usage
}

parse_params() {
  while
    (( $# > 0 ))
  do
    param="$1"
    shift
    case "$param" in
      (--backup|backup|-b)
        backup
        exit 0
        ;;
      (--update|update|-u)
        update
        exit 0
        ;;
      (--cron|cron)
        cron
        exit 0
        ;;
      (help|--help|-h)
        usage
        exit 0
        ;;
      (*)
        usage
        exit 1
        ;;
    esac
  done
}

backup() {
  check_buffer_folder
  # Check version control for the updates and notify the user
  for file in "${selected_files[@]}"; do
    cp $base_path$file -r $buffer_folder
  done

  version_control_commit

  echo "All files backed up successfully"
  exit 0
}

update() {
  cd $buffer_folder

  git pull

  for file in "${selected_files[@]}"; do
    cp -vr --backup=numbered "$base_path$file" $base_path
  done

  echo "All files updated successfully"
}

cron() {
  echo "Run on cron"
}

check_buffer_folder() {
  if [[ ! -a "$buffer_folder" ]]; then
    mkdir $buffer_folder
  fi
}

version_control_commit() {
  cd $buffer_folder

  git add -A
  git commit -v
  git push
}

usage() {
  printf "%b" "
Usage:

  dotter [options]

Options

  [[--]backup|-b]

  Backup the files on this machine to version control.

  [[--]update|-u]

    Update the files on this machine with the files from version control.

"
}

main "$@"
